version: "3.8"

services:
  minio:
    image: minio/minio
    command: server /data
    volumes:
      - .minio-data:/data
    ports:
      - "9090:9000"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 1234Abcd
  miniomc:
    image: minio/mc