version: "3.8"

services:
  minio:
    # The latest image was returning the 'found backend type fs, expected xl or xl-single' error to me
    image: minio/minio:RELEASE.2022-01-08T03-11-54Z.hotfix.f533071b4
    # The console was on a dynamic port that wasn't exposed by docker
    command: server --console-address ":9001" /data
    volumes:
      - .minio-data:/data
    ports:
      - "9090:9000"
      - "9091:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 1234Abcd
  miniomc:
    image: minio/mc